apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-clusterrole
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["pods"]
    verbs: ["watch", "list", "get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pod-watcher-clusterrole
  apiGroup: rbac.authorization.k8s.io
