---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - observability.smigula.io
  resources:
  - tetragonlogentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.smigula.io
  resources:
  - tetragonlogentries/finalizers
  verbs:
  - update
- apiGroups:
  - observability.smigula.io
  resources:
  - tetragonlogentries/status
  verbs:
  - get
  - patch
  - update
