# permissions for end users to edit tetragonlogentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tetragonsidekick
    app.kubernetes.io/managed-by: kustomize
  name: tetragonlogentry-editor-role
rules:
- apiGroups:
  - observability.smigula.io
  resources:
  - tetragonlogentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.smigula.io
  resources:
  - tetragonlogentries/status
  verbs:
  - get
